services:
  # MongoDB Service
  mongodb:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db  # Persist MongoDB data
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - illusion-network

  # Mongo Express Service
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: mongo_user
      ME_CONFIG_BASICAUTH_PASSWORD: mongo_pass
    networks:
      - illusion-network

  config-server:
    container_name: config-server
    build:
      context: ./config-server
    ports:
      - "8888:8888"
    expose:
      - "8888"
    networks:
      - illusion-network
    restart: always
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker

  discovery-server:
    container_name: discovery-server
    build:
      context: ./discovery-server
    depends_on:
      - config-server
    ports:
      - "8889:8889"
    expose:
      - "8889"
    networks:
      - illusion-network
    restart: always

  gateway:
    container_name: gateway
    build:
      context: ./gateway
    depends_on:
      - discovery-server
    ports:
      - "8893:8893"
    expose:
      - "8893"
    networks:
      - illusion-network
    restart: always

  project-service:
    container_name: project-service
    build:
      context: ./project-service
    depends_on:
      - gateway
    ports:
      - "8891:8891"
    expose:
      - "8891"
    networks:
      - illusion-network
    restart: always

  user-service:
    container_name: user-service
    build:
      context: ./user-service
    depends_on:
      - project-service
    ports:
      - "8890:8890"
    expose:
      - "8890"
    networks:
      - illusion-network
    restart: always

  api-generator-service:
    container_name: api-generator-service
    build:
      context: ./api-generator-service
    depends_on:
      - user-service
    ports:
      - "8892:8892"
    expose:
      - "8892"
    networks:
      - illusion-network
    restart: always

networks:
  illusion-network:
    driver: bridge

volumes:
  mongo:
    driver: local


