eureka:
  instance:
    hostname: discovery-server
  client:
    service-url:
      defaultZone: http://discovery-server:8880/eureka

name:
  value: demo

spring:
  cloud:
    config:
     override-system-properties: false
  data:
    mongodb:
      username: admin
      password: admin
      host: mongo_db
      port: 27027 # fixme: use 27017 in production
      database: illusionDB
      auto-index-creation: true
      authentication-database: admin

management:
  tracing:
    sampling:
      probability: 1.0
