server:
  port: 8881

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: http://user-service:8882
          predicates:
            - Path=/api/user/**

        - id: project-service-api-projects
          uri: http://project-service:8883
          predicates:
            - Path=/api/projects/**

        - id: project-service-api-endpoints
          uri: http://project-service:8883
          predicates:
            - Path=/api/endpoints/**

        - id: api-generator-service
          uri: http://api-generator-service:8884
          predicates:
            - Path=/**
