server:
  port: 9991

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: http://user-service:9992
          predicates:
            - Path=/api/user/**

        - id: project-service
          uri: http://project-service:9993/
          predicates:
            - Path=/api/projects/**

        - id: api-generator-service
          uri: http://api-generator-service:9994/
          predicates:
            - Path=/**
