server:
  port: 8892

spring:
  data:
    mongodb:
      username: admin
      password: admin
      host: localhost
      port: 27017
      database: illusionDB
      auto-index-creation: true
      authentication-database: admin
