spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/BoldBit-Labs/illusion-server/tree/main/illusion-backend/config-repo
          default-label: qa
          clone-on-start: true
        bootstrap: true
        enabled: true

server:
  port: 8888
