name: Backend Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-image:
    name: Build Backend Docker image

    strategy:
      matrix:
        image_name: ["config-server", "discovery-server", "gateway", "user-service", "project-service", "api-generator-service"]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "corretto"

      - name: Check pom.xml content
        run: |
          cat illusion-backend/${{ matrix.image_name }}/pom.xml

      - name: Build
        working-directory: illusion-backend/${{ matrix.image_name }}
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:$(date +%s)
          VERSION=$(jq -r '.version // "N/A"' pom.xml) # Handle missing version
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.image_name }} to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./illusion-backend/${{ matrix.image_name }}
          file: illusion-backend/${{ matrix.image_name }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/illusion-backend/${{ matrix.image_name }}:latest
