name: Backend Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-image:
    name: Build Backend

    strategy:
      matrix:
        image_name: ["config-server", "discovery-server", "gateway", "user-service", "project-service", "api-generator-service"]

    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "corretto"

#      - name: Build docker image ${{ matrix.image_name }}
#        working-directory: illusion-backend/${{ matrix.image_name }}
#        run: |
#          docker build . --file Dockerfile --tag "${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:$(date +%s)"
#          VERSION=$(jq -r '.version // "N/A"' pom.xml) # Handle missing version
#          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: build ${{ matrix.image_name }}
        working-directory: illusion-backend/${{ matrix.image_name }}
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: build the docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:latest

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.image_name }} to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./illusion-backend/${{ matrix.image_name }}
          file: illusion-backend/${{ matrix.image_name }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/illusion-backend/${{ matrix.image_name }}:latest
